// This file is automatically generated by i18next-cli. Do not edit manually.
interface Resources {
  "translation": {
    "dashboardChartWeatherTitle": "Average weak Temperature",
    "dashboardFooterContactTile": "Contact: info@nadin.ir",
    "dashboardFooterOwnerShipTitle": "All rights of this site are reserved for Nadin Sadr Aria Engineering Company.",
    "dashboardForecastWeatherTile": "1 Weeks Forecast",
    "dashboardLocationInputLabel": "Location",
    "dashboardSettingDarkTitle": "Dark",
    "dashboardSettingEnglishTitle": "En",
    "dashboardSettingExitTitle": "Exit",
    "dashboardSettingLanguageTitle": "Mod",
    "dashboardSettingLightTitle": "Light",
    "dashboardSettingModTitle": "Mod",
    "dashboardSettingPersianTitle": "Fa",
    "dashboardTitle": "Weather Dashboard",
    "dashboardWeatherDetailFeelTitle": "Feels like",
    "dashboardWeatherDetailHighTitle": " High: ",
    "dashboardWeatherDetailLowTitle": " Low: ",
    "loginButton": "login",
    "loginLanguageEnglishValue": "English",
    "loginLanguagePersianValue": "Persian",
    "loginLanguageTitle": "Language",
    "loginTextFieldLabel": "Username",
    "loginTitle": "Login"
  }
}

export default Resources;
